# services:
#   - type: web
#     name: ge-tender-scraper
#     env: docker
#     region: oregon # or your preferred region
#     plan: free # or standard/pro based on your needs
#     dockerfilePath: ./Dockerfile
#     dockerContext: .
#     envVars:
#       - key: PORT
#         value: 8080
#       - key: PYTHONUNBUFFERED
#         value: 1
#     healthCheckPath: /
#     autoDeploy: true

services:
  - type: web
    name: ge-tender-scraper
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9